// <auto-generated />
using System;
using BookListMVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookListMVC.Migrations
{
    [DbContext(typeof(BookListMVCContext))]
    [Migration("20191116053017_BookListMVC.Models.BookListMVCContext")]
    partial class BookListMVCModelsBookListMVCContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookListMVC.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Genre");

                    b.Property<decimal>("Price");

                    b.Property<DateTime>("PublishDate");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Book");

                    b.HasData(
                        new { Id = 1, Genre = "Genre1", Price = 20m, PublishDate = new DateTime(2012, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Book1" },
                        new { Id = 2, Genre = "Genre2", Price = 30m, PublishDate = new DateTime(2008, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), Title = "Book2" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
